bsl/stream_player/stream_player.py
bsl/stream_receiver/tests/test_stream.py
bsl/stream_receiver/tests/test_stream_receiver.py
bsl/stream_recorder/tests/test_stream_recorder.py
bsl/triggers/tests/test_software.py
bsl/utils/_testing.py

Fix #34 - Add context manager directly to the stream player.

---

bsl/stream_viewer/scope/tests/test_scope_eeg.py
bsl/utils/find_event_channel.py
bsl/utils/io.py

Fix #43.
The EEG scope was assumed that there is only one trigger channel at index 0 in a given stream.
Fix this assumption and add validation testing for the scope.

Fix #43 - Add validation test for EEG scope.

---

bsl/stream_receiver/stream_receiver.py

OpenViBE Acquisition Server allows to send LSL stream but the stream info types are 'signal' and 'marker'.

Update stream_receiver.py for OpenViBE Acquisition EEG signal output

---

bsl/lsl/stream_inlet.py
bsl/stream_player/stream_player.py
bsl/stream_receiver/stream_receiver.py
bsl/stream_receiver/tests/test_stream_receiver.py
bsl/stream_recorder/tests/test_stream_recorder.py
bsl/utils/tests/test_docs.py

As reported and corrected in https://github.com/labstreaminglayer/pylsl/pull/61

[BUG] Fix pull_chunk size overflow error

---

bsl/stream_viewer/control_gui/_ui_control.py
bsl/stream_viewer/control_gui/control_eeg.py
bsl/stream_viewer/control_gui/settings/settings_scope_eeg.ini
bsl/stream_viewer/scope/scope_eeg.py
bsl/utils/lsl.py

Adds a de trending option, using a 2 seconds buffer.
Adds the possibility to uncheck the BP filter.

[ENH] Add disabling of BP filter and detrending option to the StreamViewer

---

.github/workflows/pylsl.yml

Compare to known version of pylsl to catch updates in pylsl.

Add workflow to compare checksum of pylsl

---

bsl/utils/tests/test_test.py

Confirms that match_stream_and_raw_data is not responsibe for #112.

Add test for match_stream_and_raw_data utility

---

bsl/stream_viewer/backends/pyqtgraph.py
bsl/stream_viewer/control_gui/_control.py
bsl/stream_viewer/control_gui/_ui_control.py
bsl/stream_viewer/control_gui/control_eeg.py
bsl/stream_viewer/stream_viewer.py
pyproject.toml

Tested with PySide2, PyQt5, PySide6, PyQt6.
Closes #114

Replace PyQt5 with qtpy

---

bsl/stream_viewer/scope/scope_eeg.py
bsl/stream_viewer/stream_viewer.py

Fix scaling and logging of legacy StreamViewer

---

bsl/datasets/sample-registry.txt
bsl/datasets/sample.py

Add sample dataset for tutorials.

Add sample dataset

---

bsl/conftest.py
bsl/lsl/tests/test_functions.py
bsl/stream/_base.py
bsl/stream/stream_lsl.py
bsl/stream/tests/test_stream_lsl.py

Add rereferencing Stream function

---

pyproject.toml
setup.py

Remove legacy setup.py

---

.github/workflows/doc.yml
doc/Makefile
doc/conf.py

Improve documentation workflow

---

.github/workflows/pylsl.yml
mne_lsl/lsl/constants.py
mne_lsl/lsl/stream_outlet.py
mne_lsl/lsl/tests/test_stream_outlet.py

Add support for 'timestamp' array in a push operation

---

doc/_sphinxext/sphinx_remove_toctrees.py
doc/conf.py
pyproject.toml

Add local sphinx-remove-toctrees extension

---

doc/conf.py
mne_lsl/_typing.py
mne_lsl/lsl/functions.py
mne_lsl/lsl/load_liblsl.py
mne_lsl/lsl/stream_info.py
mne_lsl/lsl/stream_inlet.py
mne_lsl/lsl/stream_outlet.py
mne_lsl/player/_base.py
mne_lsl/player/player_lsl.py
mne_lsl/stream/_base.py
mne_lsl/utils/_docs.py
mne_lsl/utils/_tests.py
mne_lsl/utils/config.py
mne_lsl/utils/meas_info.py

Fixing type-hints and Pylance warnings in VScode.

Improve type-hints

---

.github/workflows/stubs.yaml

Fix stub workflow

---

.github/workflows/pytest.yaml

Restore pip-pre release workflow with numpy 2.0

---

.github/workflows/publish.yaml
.github/workflows/pytest.yaml
pyproject.toml
tools/stubgen.py

Add CIs on arm64 platform for macOS

---

mne_lsl/stream/_base.py

Add missing pick default in #218

Add missing default to filters

---

.github/workflows/doc.yaml
.github/workflows/publish.yaml
doc/changes/latest.rst
mne_lsl/stream/_base.py
mne_lsl/stream/_filters.py
mne_lsl/stream/tests/test_filters.py
mne_lsl/stream/tests/test_stream_lsl.py

Add notch filtering

---

doc/api/lsl (low-level).rst
doc/make.bat
doc/resources/pylsl.rst
mne_lsl/lsl/tests/test_functions.py
mne_lsl/lsl/tests/test_stream_info.py
mne_lsl/lsl/tests/test_stream_inlet.py
mne_lsl/lsl/tests/test_stream_outlet.py
mne_lsl/player/tests/test_player_lsl.py
mne_lsl/stream/_base.py
mne_lsl/utils/tests/test_meas_info.py
tutorials/10_low_level_API.py

Improve documentation of performance differences between pylsl and mne.lsl

---

mne_lsl/conftest.py
mne_lsl/datasets/tests/test_datasets.py
mne_lsl/lsl/tests/test_load_liblsl.py
mne_lsl/lsl/tests/test_stream_info.py
mne_lsl/lsl/tests/test_stream_inlet.py
mne_lsl/lsl/tests/test_stream_outlet.py
mne_lsl/player/_base.py
mne_lsl/stream/_base.py
mne_lsl/stream/stream_lsl.py
mne_lsl/stream/tests/test_filters.py
mne_lsl/stream/tests/test_stream_lsl.py
mne_lsl/stream_viewer/backends/_backend.py
mne_lsl/stream_viewer/backends/pyqtgraph.py
mne_lsl/stream_viewer/control_gui/_control.py
mne_lsl/stream_viewer/scope/_scope.py
mne_lsl/utils/tests/test_docs.py
mne_lsl/utils/tests/test_logs.py
mne_lsl/utils/tests/test_test.py
pyproject.toml

Enable G, LOG, NPY, PIE, PT, T20 rule sets.

Enable additional ruff rules

---

.github/workflows/pytest.yaml
.gitignore
doc/changes/latest.rst
mne_lsl/stream_viewer/backends/pyqtgraph.py
mne_lsl/stream_viewer/control_gui/_ui_control.py
mne_lsl/stream_viewer/control_gui/control_eeg.py
mne_lsl/stream_viewer/control_gui/settings/settings_scope_eeg.ini

Improve legacy viewer scaling

---

.github/release.yaml
.pre-commit-config.yaml
doc/api/legacy.rst
doc/api/lsl (low-level).rst
doc/api/most-used classes.rst
doc/api/utilities.rst
doc/changes/latest.rst
doc/conf.py
doc/make.bat
examples/00_player_separate_process.py
examples/10_peak_detection.py
mne_lsl/datasets/sample.py
mne_lsl/lsl/constants.py
mne_lsl/lsl/stream_info.py
mne_lsl/lsl/stream_inlet.py
mne_lsl/lsl/stream_outlet.py
mne_lsl/player/_base.py
mne_lsl/player/player_lsl.py
mne_lsl/stream/_base.py
mne_lsl/stream/stream_lsl.py
mne_lsl/stream/tests/test_stream_lsl.py
mne_lsl/utils/_deprecation.py
pyproject.toml
tutorials/30_stream_manual.py

Closes #262 
Add a manual acquisition method which does not run a background thread.

Add manual acquisition method

---

doc/_sphinxext/sphinx_remove_toctrees.py
doc/conf.py
pyproject.toml

Revert "Rm use of custom sphinx-remove-toctrees (#240)" (#284)

---

pyproject.toml

include `spaces_before_inline_comment = 2`

Update toml-sort config

---

doc/development/changes/latest.rst
mne_lsl/conftest.py
mne_lsl/lsl/load_liblsl.py

Add configuration variable MNE_LSL_LIB_FOLDER to control the download directory

---

doc/development/changes/latest.rst

Update the missed changelog entries for #351

Update changelog entries

---

doc/development/changes/authors.inc
doc/development/changes/latest.rst
tutorials/00_introduction.py
tutorials/20_player_annotations.py

Sorry, same as #388, just realised I missed one on the same page.
Gave a look this time through the other tutorials and examples and didn't find other instances.

Fix intersphinx link in tutorial

---

.mailmap
src/mne_lsl/stream/epochs.py
src/mne_lsl/stream/epochs.pyi

Minor documentation fixes triggered by #414

Minor documentation fixes

---

src/mne_lsl/stream/base.py
src/mne_lsl/stream/base.pyi
src/mne_lsl/stream/stream_lsl.py
src/mne_lsl/stream/stream_lsl.pyi
tests/stream/test_stream_lsl.py

Hash streams from a unique identifier.

Add support for stream hashing and usage as dictionary keys

---

paper/paper.bib
paper/paper.md

Closes #430 
@teonbrooks Hello! This PR addresses #430 and your initial comments in #431. Let me know if you agree with the changes.

Update JOSS paper

---

doc/development/changes/latest.rst
doc/links.inc
doc/resources/install.rst
setup.py

Pin liblsl build to VS2019 toolset and update Windows install instructions

---

paper/paper.md

Closes #443 
@matthiasdold Here is a revised `pylsl` section. Let me know if you want further changes.

Improve JOSS paper section about `pylsl`
